global:
  scrape_interval: 5s # Fréquence de récolte des métriques

scrape_configs:
  - job_name: 'cadvisor' # Le nom de notre job de monitoring
    static_configs:
      # On dit à Prometheus d'aller interroger cAdvisor sur le port 8080
      - targets: ['cadvisor:8080']
