version: "3.8"

services:
  server:
    image: server-img:latest
    container_name: server
    command: sleep infinity
    tty: true
    networks:
      - net-ares

  client:
    image: client-img:latest
    container_name: client
    command: sleep infinity
    tty: true
    networks:
      - net-ares

  sonde:
    image: sonde-img:latest
    container_name: sonde
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/debian/PRES/captures_trafic/trafic_topo3:/data
    command: sleep infinity
    tty: true
    networks:
      - net-ares

  router1:
    image: frr-rip-img:latest
    container_name: router1
    privileged: true
    tty: true
    networks:
      - net-ares

  router2:
    image: frr-rip-img:latest # Utilise la même image que router1
    container_name: router2
    privileged: true
    tty: true
    networks:
      - net-ares

prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - net-ares

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - net-ares

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - net-ares

networks:
  net-ares:
    name: net-ares
    driver: bridge
